let postlist =
[ { key: 'IONIC',
    value: 
     [ { fileName: '2017-05-07-canonRO',
         title: 'CanonRO',
         category: 'IONIC',
         description: 'Ionic app: canon van de geschiedenis van de ruimtelijke ordening.',
         featuredImg: '/img/featured-img/canonRO-200.jpg' },
       { fileName: '2017-02-14-mijn-uitgaven',
         title: 'MijnUitgaven',
         category: 'IONIC',
         description: 'Ionic 2 demo: huishoudboekje. Overzicht van maandelijkse uitgaven, geordend in verschillende rubrieken.',
         featuredImg: '/img/featured-img/mijn-uitgaven-200.jpg' } ] },
  { key: 'ANGULAR',
    value: 
     [ { fileName: '2016-11-08-boeken',
         title: 'Boeken',
         category: 'ANGULAR',
         description: 'Angular demo: boekencatalogus. Voeg zelf boeken toe vanuit openbare online database.',
         featuredImg: '/img/featured-img/boeken-200.jpg' },
       { fileName: '2016-09-05-kopie-id',
         title: 'KopieID voor desktop',
         category: 'ANGULAR',
         description: 'Gebaseerd op de KopieID-app van de Rijksoverheid. Met deze variant maak je op desktop een kopie van je paspoort met afgeschermd burgerservicenummer.',
         featuredImg: '/img/featured-img/kopieID-200.jpg' },
       { fileName: '2016-07-13-welke-gemeenten-doen-mee',
         title: 'Welke gemeenten doen mee?',
         category: 'ANGULAR',
         description: 'Angular app om bij te houden welke gemeenten meedoen aan een project.',
         featuredImg: '/img/featured-img/welke-gemeenten-doen-mee-200.jpg' } ] },
  { key: 'D3',
    value: 
     [ { fileName: '2014-11-29-uiterwaarden',
         title: 'Uiterwaarden',
         category: 'D3',
         description: 'Interactieve kaart met waterhoogten in de uiterwaarden.',
         featuredImg: '/img/featured-img/uiterwaarden-200.jpg' },
       { fileName: '2014-05-28-winsten-zelfstandige-artsen',
         title: 'Winsten zelfstandige artsen',
         category: 'D3',
         description: 'Interactieve lijngrafiek; staafdiagram met animatie. Over de inkomens van zelfstandig gevestigde medisch specialisten.',
         featuredImg: '/img/featured-img/winsten-zelfstandige-artsen-200.jpg' },
       { fileName: '2014-04-29-locaties-op-de-kaart',
         title: 'Locaties op de kaart',
         category: 'D3',
         description: 'Waar kun je je boodschappen doen in Wageningen? Om het makkelijk te maken kun je zoeken op het soort winkel.',
         featuredImg: '/img/featured-img/locaties-op-de-kaart-200.jpg' },
       { fileName: '2014-04-11-koeien-varkens-kippen',
         title: 'Koeien, varkens, kippen',
         category: 'D3',
         description: 'Interactief staafdiagram met hoeveelheden dieren in de agrarische sector in een aantal EU-landen.',
         featuredImg: '/img/featured-img/koeien-varkens-kippen-200.jpg' },
       { fileName: '2014-03-27-verkiezingsuitslagen',
         title: 'Verkiezings\u00ADuitslagen',
         category: 'D3',
         description: 'Interactieve kaart met uitslagen gemeente\u00ADraads\u00ADverkiezingen in de vier grote steden.',
         featuredImg: '/img/featured-img/verkiezingsuitslagen-200.jpg' },
       { fileName: '2013-09-23-eindredacteur-aan-het-werk',
         title: 'Eindredacteur aan het werk',
         category: 'D3',
         description: 'Start de demo en volg stap voor stap het ambacht van een redacteur.',
         featuredImg: '/img/featured-img/eindredacteur-aan-het-werk-200.jpg' },
       { fileName: '2013-06-12-langdurige-aandoeningen',
         title: 'Langdurige aandoeningen',
         category: 'D3',
         description: 'Reeksen lijngrafieken over de meest voorkomende chronische aandoeningen.',
         featuredImg: '/img/featured-img/langdurige-aandoeningen-200.jpg' },
       { fileName: '2012-06-12-operaties-in-het-ziekenhuis',
         title: 'Operaties in het ziekenhuis',
         category: 'D3',
         description: 'Bekijk per operatie-soort hoe vaak deze jaarlijks is uitgevoerd.',
         featuredImg: '/img/featured-img/operaties-200.jpg' } ] },
  { key: 'WEBSITES',
    value: 
     [ { fileName: '2014-11-06-valleilijn',
         title: 'Valleilijn',
         category: 'WEBSITES',
         description: 'Valleilijn.nl geeft reizigersinformatie over de OV-verbinding Amersfoort – Ede – Wageningen.',
         featuredImg: '/img/featured-img/valleilijn-200.jpg' },
       { fileName: '2014-10-16-publicspace',
         title: 'Public Space',
         category: 'WEBSITES',
         description: 'Public Space is een onafhankelijke denktank gericht op maatschappelijk ondernemen.',
         featuredImg: '/img/featured-img/publicspace-200.jpg' },
       { fileName: '2014-07-08-zodra',
         title: 'Zodra',
         category: 'WEBSITES',
         description: 'Zodra.nl is de website van mijn eigen tekstbureau. Eén pagina slechts, puur in HTML en CSS.',
         featuredImg: '/img/featured-img/zodra-200.jpg' } ] } ];

exports.postlist = postlist;