let postlist =
[ { key: 'Webapps',
    catDescription: 'Webapps bekijk je in de browser op smartphone, tablet of pc. Het onderscheid tussen websites en webapps is diffuus. Een webapp is gericht op doen en interactie. Een website op bekijken of lezen van content.',
    value: 
     [ { fileName: '2016-11-08-boeken',
         title: 'Boeken',
         category: 'Webapps',
         description: 'Boekencatalogus app. Voeg zelf boeken toe vanuit openbare online database.',
         featuredImg: '/img/featured-img/boeken-200.jpg' },
       { fileName: '2016-09-05-kopie-id',
         title: 'KopieID voor desktop',
         category: 'Webapps',
         description: 'Variant op de KopieID-app van de Rijksoverheid. Je kunt op mobiel én desktop een kopie van je paspoort met afgeschermd burgerservicenummer maken.',
         featuredImg: '/img/featured-img/kopieID-200.jpg' },
       { fileName: '2016-07-13-welke-gemeenten-doen-mee',
         title: 'Welke gemeenten doen mee?',
         category: 'Webapps',
         description: 'App om bij te houden welke gemeenten meedoen aan een project.',
         featuredImg: '/img/featured-img/welke-gemeenten-doen-mee-200.jpg' } ] },
  { key: 'Hybride apps',
    catDescription: 'Hybride apps bekijk je op smartphone of tablet. Het zijn eigenlijk webapps met een omhulsel. Daardoor hoef je ze niet in de browser te bekijken maar zijn het volwaardige apps op je mobiele apparaat.',
    value: 
     [ { fileName: '2017-05-07-canonRO',
         title: 'CanonRO',
         category: 'Hybride apps',
         description: 'Ionic app: canon van de geschiedenis van de ruimtelijke ordening.',
         featuredImg: '/img/featured-img/canonRO-200.jpg' },
       { fileName: '2017-02-14-mijn-uitgaven',
         title: 'MijnUitgaven',
         category: 'Hybride apps',
         description: 'Ionic 2 demo: huishoudboekje. Overzicht van maandelijkse uitgaven, geordend in verschillende rubrieken.',
         featuredImg: '/img/featured-img/mijn-uitgaven-200.jpg' } ] },
  { key: 'Interactieve kaarten',
    catDescription: 'Interactieve kaarten kunnen onderdeel zijn van een app of website. Ze laten locaties of data zien. Je kunt zelf de locaties of data selecteren.',
    value: 
     [ { fileName: '2014-04-29-locaties-op-de-kaart-leaflet',
         title: 'Locaties op de kaart (1)',
         category: 'Interactieve kaarten',
         description: 'Waar is er een supermarkt, een bakker, een toko? Je ziet het op een interactieve kaart. Gemaakt met Leaflet en NLMaps.',
         featuredImg: '/img/featured-img/locaties-op-de-kaart-leaflet-200.jpg' },
       { fileName: '2014-04-29-locaties-op-de-kaart-googlemaps',
         title: 'Locaties op de kaart (2)',
         category: 'Interactieve kaarten',
         description: 'Waar is er een supermarkt, een bakker, een toko? Je ziet het op een interactieve kaart. Gemaakt met Google Maps.',
         featuredImg: '/img/featured-img/locaties-op-de-kaart-googlemaps-200.jpg' },
       { fileName: '2014-03-27-verkiezingsuitslagen',
         title: 'Verkiezings\u00ADuitslagen',
         category: 'Interactieve kaarten',
         description: 'Interactieve kaart met uitslagen gemeente\u00ADraads\u00ADverkiezingen in de vier grote steden.',
         featuredImg: '/img/featured-img/verkiezingsuitslagen-200.jpg' } ] },
  { key: 'Animaties',
    catDescription: 'Animaties kunnen onderdeel zijn van een app of website. Wat ze laten zien kan erg uiteenlopen. Door het bewegend beeld trekken ze aandacht.',
    value: 
     [ { fileName: '2014-11-29-uiterwaarden',
         title: 'Uiterwaarden',
         category: 'Animaties',
         description: 'Interactieve kaart met waterhoogten in de uiterwaarden. Laat het water stijgen en en weer zakken.',
         featuredImg: '/img/featured-img/uiterwaarden-200.jpg' },
       { fileName: '2014-04-11-koeien-varkens-kippen',
         title: 'Koeien, varkens, kippen',
         category: 'Animaties',
         description: 'Diagram laat zien hoeveel dieren er zijn in de agrarische sector in een aantal EU-landen.',
         featuredImg: '/img/featured-img/koeien-varkens-kippen-200.jpg' },
       { fileName: '2013-09-23-eindredacteur-aan-het-werk',
         title: 'Eindredacteur aan het werk',
         category: 'Animaties',
         description: 'Start de demo en volg stap voor stap het ambacht van een redacteur.',
         featuredImg: '/img/featured-img/eindredacteur-aan-het-werk-200.jpg' } ] },
  { key: 'Data in beeld',
    catDescription: 'Data in beeld, oftewel datavisualisaties, kunnen onderdeel zijn van een app of website. Ze geven inzicht in omvangrijke of complexe data.',
    value: 
     [ { fileName: '2014-05-28-winsten-zelfstandige-artsen',
         title: 'Winsten zelfstandige artsen',
         category: 'Data in beeld',
         description: 'Interactieve lijngrafiek; staafdiagram met animatie. Over de inkomens van zelfstandig gevestigde medisch specialisten.',
         featuredImg: '/img/featured-img/winsten-zelfstandige-artsen-200.jpg' },
       { fileName: '2013-06-12-langdurige-aandoeningen',
         title: 'Langdurige aandoeningen',
         category: 'Data in beeld',
         description: 'Cijfers over de meest voorkomende chronische aandoeningen in beeld.',
         featuredImg: '/img/featured-img/langdurige-aandoeningen-200.jpg' },
       { fileName: '2012-06-12-operaties-in-het-ziekenhuis',
         title: 'Operaties in het ziekenhuis',
         category: 'Data in beeld',
         description: 'Bekijk per operatie hoe vaak deze jaarlijks is uitgevoerd.',
         featuredImg: '/img/featured-img/operaties-200.jpg' } ] },
  { key: 'WEBSITES',
    catDescription: undefined,
    value: 
     [ { fileName: '2014-11-06-valleilijn',
         title: 'Valleilijn',
         category: 'WEBSITES',
         description: 'Valleilijn.nl geeft reizigersinformatie over de OV-verbinding Amersfoort – Ede – Wageningen.',
         featuredImg: '/img/featured-img/valleilijn-200.jpg' },
       { fileName: '2014-10-16-publicspace',
         title: 'Public Space',
         category: 'WEBSITES',
         description: 'Public Space is een onafhankelijke denktank gericht op maatschappelijk ondernemen.',
         featuredImg: '/img/featured-img/publicspace-200.jpg' } ] } ];

exports.postlist = postlist;